import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { Invoice, Client, Job } from '@/types';
import { formatCurrency, formatDate } from './utils';
import autoTable from 'jspdf-autotable';

interface InvoiceGenerationParams {
  invoice: Invoice;
  client: Client;
  job?: Job;
}

export const generateInvoicePdf = ({
  invoice,
  client,
  job
}: InvoiceGenerationParams): jsPDF => {
  // Create a new PDF document
  const doc = new jsPDF();
  
  // Set background color with gradient-like effect (simulate gradient with shapes)
  // First draw a light background
  doc.setFillColor(240, 249, 255); // Light blue color
  doc.rect(0, 0, 210, 297, 'F');
  
  // Add a decorative header strip with accent color
  doc.setFillColor(59, 130, 246); // blue-500
  doc.rect(0, 0, 210, 25, 'F');
  
  // Add a more subtle accent stripe
  doc.setFillColor(139, 92, 246); // purple-500
  doc.rect(0, 25, 210, 3, 'F');
  
  // Set up document metadata
  doc.setProperties({
    title: `Invoice ${invoice.number}`,
    subject: 'Invoice',
    author: 'Boper',
    keywords: 'invoice, payment',
    creator: 'Boper Invoice System'
  });

  // Add company logo or name at the top
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text('BOPER', 14, 17);
  
  // Tagline
  doc.setFontSize(10);
  doc.text('Your Job Management Solution', 75, 17);
  
  // Set default text color for the rest of the document
  doc.setTextColor(0, 0, 0);
  
  // Add invoice details
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 14, 40);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Invoice Number: ${invoice.number}`, 14, 50);
  doc.text(`Date: ${formatDate(invoice.createdAt)}`, 14, 55);
  doc.text(`Due Date: ${formatDate(invoice.dueDate)}`, 14, 60);
  doc.text(`Status: ${invoice.status.toUpperCase()}`, 14, 65);
  
  // Client details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 14, 80);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(client.name, 14, 85);
  doc.text(client.email, 14, 90);
  if (client.phone) {
    doc.text(client.phone, 14, 95);
  }
  if (client.address) {
    const addressLines = client.address.split(',');
    addressLines.forEach((line, index) => {
      doc.text(line.trim(), 14, 100 + (index * 5));
    });
  }
  
  // Job details if available
  if (job) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Job Details:', 120, 80);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(job.name, 120, 85);
    if (job.description) {
      // Handle potentially long descriptions by wrapping text
      const splitDescription = doc.splitTextToSize(job.description, 70);
      doc.text(splitDescription, 120, 90);
    }
  }
  
  // Invoice items table
  autoTable(doc, {
    startY: 120,
    head: [['Description', 'Amount']],
    body: [
      [job ? job.name : 'Services', formatCurrency(invoice.amount)],
    ],
    foot: [
      ['Total', formatCurrency(invoice.amount)]
    ],
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    footStyles: {
      fillColor: [240, 240, 240],
      fontStyle: 'bold'
    },
    theme: 'grid'
  });
  
  // Add notes if available
  if (invoice.notes) {
    const currentY = (doc as any).lastAutoTable.finalY + 20;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Notes:', 14, currentY);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const splitNotes = doc.splitTextToSize(invoice.notes, 180);
    doc.text(splitNotes, 14, currentY + 5);
  }
  
  // Add payment instructions at the bottom of the page
  const paymentY = 250;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Payment Information:', 14, paymentY);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Please make payment by the due date.', 14, paymentY + 5);
  doc.text('Thank you for your business!', 14, paymentY + 10);
  
  // Add footer
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by Boper - Your Job Management Solution', 65, 285);
  doc.text('getboper.com', 90, 290);

  return doc;
};

export const downloadInvoicePdf = (params: InvoiceGenerationParams): void => {
  const doc = generateInvoicePdf(params);
  doc.save(`Invoice_${params.invoice.number}.pdf`);
};

// To open PDF in a new tab
export const openInvoicePdf = (params: InvoiceGenerationParams): void => {
  const doc = generateInvoicePdf(params);
  const pdfBlob = doc.output('blob');
  const pdfUrl = URL.createObjectURL(pdfBlob);
  window.open(pdfUrl, '_blank');
};